#!/usr/bin/env lua
--
-- Source of truth for the Hyprland config.
--
-- Hyprland cannot read Lua, so this script renders the modules under lua/sections/
-- into hyprland.generated.conf. Edit the modules, then run:
--
--     lua hyprland.lua && hyprctl reload
--
-- To make Hyprland actually use the output, add this line to hyprland.conf:
--
--     source = ~/.config/hypr/hyprland.generated.conf
--

local script_dir = arg[0]:match("(.*)/") or "."
package.path = ("%s/lua/?.lua;%s"):format(script_dir, package.path)

local Builder = require("lib.builder")

-- Rendered in this order.
local SECTIONS = {
    "monitors",
    "programs",
    "autostart",
    "environment",
    "cursor",
    "look_and_feel",
    "input",
    "keybindings",
    "windowrules",
}

local OUTPUT = script_dir .. "/hyprland.generated.conf"

local b = Builder.new()

b:comment(("#"):rep(86))
b:comment("AUTOGENERATED BY hyprland.lua -- DO NOT EDIT THIS FILE.")
b:comment("Edit the modules in lua/sections/ and re-run: lua hyprland.lua")
b:comment(("#"):rep(86))
b:blank()

for _, name in ipairs(SECTIONS) do
    require("sections." .. name)(b)
end

local f = assert(io.open(OUTPUT, "w"))
f:write(b:tostring())
f:close()

io.write(("Wrote %s (%d sections)\n"):format(OUTPUT, #SECTIONS))
io.write("Reload with: hyprctl reload\n")
